# SPDX-FileCopyrightText: 2020 Benedict Harcourt <ben.harcourt@harcourtprogramming.co.uk>
#
# SPDX-License-Identifier: CC0-1.0

name: Linting

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run:  pip install -r requirements.txt

    - name: Install Linters
      run:  pip install flake8 mypy black

    - name: Run Linters
      uses: samuelmeuli/lint-action@v1
      with:
        github_token: ${{ secrets.github_token }}

        black:    true
        black_dir: tools

        flake8:      true
        flake8_args: --max-complexity=8 --max-line-length=100
        flake8_dir:  tools

        mypy:     true
        mypy_dir: tools
