# SPDX-FileCopyrightText: 2020 Benedict Harcourt
# SPDX-FileCopyrightText: 2020 Benedict Harcourt <ben.harcourt@harcourtprogramming.co.uk>
#
# SPDX-License-Identifier: CC0-1.0

name: SPDX Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  spdx-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v1.1
